# Generated by Django 4.1.3 on 2022-11-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("User_name", models.CharField(default="", max_length=50)),
                ("Father_name", models.CharField(default="", max_length=50)),
                ("Email", models.CharField(default="", max_length=50)),
                ("Password", models.CharField(default="", max_length=50)),
                ("About_user", models.TextField()),
                ("Dath_Of_Birth", models.DateTimeField(default="", max_length=50)),
                (
                    "prof_pic",
                    models.ImageField(
                        default="", max_length=50, upload_to="profile_pics"
                    ),
                ),
            ],
        ),
    ]
